version: '3.8'

networks:
  fixed_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16

services:
  spring4shell:
    build: ./spring
    container_name: spring
    ports:
      - "8080:8080"
    networks:
      fixed_net:
        ipv4_address: 10.10.0.2
    logging:
      driver: syslog
      options:
        syslog-facility: "local0"
        tag: "docker-spring"

  client:
    build: ./app
    container_name: client
    restart: unless-stopped
    depends_on:
      - spring4shell
    networks:
      fixed_net:
        ipv4_address: 10.10.0.3
    logging:
      driver: syslog
      options:
        syslog-facility: "local0"
        tag: "docker-client"

  tomcat:
    image: tomcat:9.0
    container_name: tomcat
    ports:
      - "8081:8080"
    networks:
      fixed_net:
        ipv4_address: 10.10.0.4
    logging:
      driver: syslog
      options:
        syslog-facility: "local0"
        tag: "docker-tomcat"
